### ISSUE TITLE
Marketplace only showing 4 assets

### ISSUE THREAD

**Issue by LavaHoleD** [master-technology/UnrealLauncher#1]
No idea what it's causing this.
I wanted to install the Unreal Engine Learning kit. 
If I try to search anything else that is not listed here it will not display.
Yes I have already restarted the applications multiple times.
I'm on arch linux.
![immagine](https://user-images.githubusercontent.com/73123805/224508411-5222b37f-1e29-4017-8ac4-4d7ee9991567.png)

**Comment by LavaHoleD** [comment]
Refreshing assets will not work.

**Comment by NathanaelA** [comment]
Unless I am misunderstanding you, you are looking for the market place asset page, not the assets that you actually own.  Correct?

In this specific case you would want to go to the https://www.unrealengine.com/marketplace/en-US/product/unreal-learning-kit-rube-goldberg-machines page, on the marketplace.  Add it to your cart (or click the free button).  That should add it to your "owned" assets, then if you use the launcher (do a refresh) it should show up in your owned assets and allow you to install it.

A market place integration "Tab" will be coming, but it has a lot of weird corner cases that I haven't had time to fix so it is disabled in the launcher currently...   So all "Marketplace" interactions currently need to be done with a browser.

**Comment by LavaHoleD** [comment]
Ah I see! I thought the assets tab was referred to the marketplace, my apologies. Thank you very much for the information and keep up the good work!
