### ISSUE TITLE
Issue detecting projects

### ISSUE THREAD

**Issue by LavaHoleD** [master-technology/UnrealLauncher#2]
Welp here I am making an issue again, I hope I'm also wrong this time.
I have refreshed both assets and projects (I have created a project in the meantime). Initially nothing changed but when I restarted the launcher the new assets started showing, however, no update on projects. It says that if the projects are not detected then I have to read the docs which apparently have troubleshooting information (I cannot find them, checked both here on github and the official website, maybe I'm missing something again). The engine is being detected.

This time I will not close this issue too early so I don't end in creating too many issues if something happens again.

**Comment by NathanaelA** [comment]
Nah, no such thing as too many issues.     
 Docs & settings pane are forthcoming, settings pane is the answer, as you just need to tell the launcher where your projects are stored if it can't auto-detect it.   Normally it can figure it out based on where your unreal engines last project was opened...

 However if it can't -- you can use the command line `unreallauncher SET PROJECT_PATH "path|path|.."`  where each `path` is pointed to a root directory of where you keep your projects, most people will probably only have one root path, but the launcher supports unlimited root paths....       So if you keep your projects in:
`/home/user/Documents/Unreal Projects/` you would use that as your root path...

**Comment by NathanaelA** [comment]
Oh, and before you "SET" the value, can you do a `unreallauncher GET PROJECT_PATH` and tell me what it thinks it is, maybe I have a bug somewhere and you ran into it...  ;-)

**Comment by LavaHoleD** [comment]
Hello! Sorry for the late response, I just got on the PC right now.
So I first ran `unreallauncher GET PROJECT_PATH` and said that it's undefined. 
![immagine](https://user-images.githubusercontent.com/73123805/224558139-3a89f5ec-46a0-4cf9-a128-d5fa7b821d58.png)
When I ran it in GUI mode it said in the console that I had to at least set one project path, so either it did not find one or if it's supposed to set a path as default, it did not. Most surely it couldn't simply find one but that's reasonable as the documents folder is named a different way.

Now I got an issue tho. When I try to set the project path, it returns the `--help` function (I suppose it means that it does not recognize the command).
I have also tried `/home/Documenti/Unreal Projects/` (as I have set my installation to be in italian, every default common folder was automatically named in italian) but it did not work.
![immagine](https://user-images.githubusercontent.com/73123805/224558429-19b871b6-9efc-47b3-8f50-f3df038686c0.png)

**Comment by NathanaelA** [comment]
You need to Quote the path your are setting as ALL the OS's will split on the spaces and think it is a new command.   So you should do:

`unreal-launcher.AppImage SET PROJECT_PATH "/home/Documenti/Unreal Projects/"`
 
Hmm, well your screen shots did show a different bug, so thanks!    -- You shouldn't be seeing the `[` `]` characters on the console, it should be a single line of text for each CLI option...

**Comment by LavaHoleD** [comment]
> You need to Quote the path your are setting as ALL the OS's will split on the spaces and think it is a new command

Ahh I see! Didn't know that, thank you very much! By the way, unless I misunderstood, it does not seem to have unlimited amount of project paths, as I tried to add multiple but it would only set the latest I had asked for.

> Hmm, well your screen shots did show a different bug, so thanks!

Oh, no problem! I'm glad to help!

**Comment by NathanaelA** [comment]
So basically if you want to have multiple "parent" paths, so say you have some projects in:
`/home/Documenti/Unreal Projects/` and you have others in `/Unreal/projects/` and say still more in `/mnt/Unreal/Projects/` then you can do this:
```cli
unreal-launcher.AppImage SET PROJECT_PATH "/home/Documenti/Unreal Projects/|/Unreal/projects/|/mnt/Unreal/Projects/"

Make sure you quote the entire string, and use a PIPE (|) character to separate the paths.

**Comment by NathanaelA** [comment]
v0.0.11 now has a settings screen for easy modification of paths.  ;-)        No more need to use the CLI to set anything up.

The same "|" pipe symbol is still used to separate paths.
