### ISSUE TITLE
Project details display

### ISSUE THREAD

**Issue by apoisonedgift** [master-technology/UnrealLauncher#3]
When you click on the project to launch it, it appears that under some circumstances, the project details are offscreen in the window. For instance - if I select a project in the default projects folder it looks fine: 
![image](https://user-images.githubusercontent.com/7634496/233237062-6c3dbc98-9339-4f7e-97cf-755829b49db9.png)

But if I select one in another folder, the "Launch" button is half hidden:

![image](https://user-images.githubusercontent.com/7634496/233237259-b8b3d906-eae8-4b9b-9b8d-cfa4b9c22921.png)

This is on the windows client, 0.0.11

An additional note - if you have enough projects listed to require scrolling, the project details appear at the top and you have to scroll back up to see them. It'd be nice if that could be a floating window that ignored the scroll IMO

![image](https://user-images.githubusercontent.com/7634496/233237617-fcd4c41b-6c91-4ad3-b918-61e3a5646ec0.png)

**Comment by NathanaelA** [comment]
Thank you for the bug report, both issues are fixed in v0.0.12, in addition the issue was tested in the other tabs and fixed. ;-)
