### ISSUE TITLE
Editor says not enough space on installing 5.1.1

### ISSUE THREAD

**Issue by tryhardsnipehrd** [master-technology/UnrealLauncher#4]
As the title says, I tried to install Unreal Engine 5.1.1 through the UnrealLauncher on Ubuntu 22.10. I am installing to an external SSD that has more than enough space, approximately 960 Gigabytes free. 
Is there any reasons that this would be occurring?

**Comment by NathanaelA** [comment]
Interesting, it should be detecting how much disk space you have available for the directory based on the mount point you are putting it into.      

Can you do a `df -Pk /path/you/used/for/the/destination` and tell me what it says?  

You can also override the disk space check by doing:
`./unreal-launcher SET IGNORE_DISK_SPACE true`

Then run the launcher again --- I need to expose this setting in the settings dialog.

**Comment by tryhardsnipehrd** [comment]
![image](https://user-images.githubusercontent.com/57113411/236231127-b9c7e8ee-0ef2-41b8-9e56-0625e7ad99e6.png)
Attached is the image of the command you stated, I'll attempt running it with the options you suggested!

**Comment by NathanaelA** [comment]
This should be fixed in v0.013!
